/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistema_academico2;

/**
 *
 * @author gustavo
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Texto_Bem_vindo = new javax.swing.JLabel();
        Texto_AcesseConta = new javax.swing.JLabel();
        Texto_AcesseConta1 = new javax.swing.JLabel();
        TextoCrieConta = new javax.swing.JLabel();
        Nome_Usuario = new javax.swing.JTextField();
        Senha = new javax.swing.JPasswordField();
        TextoUsuario = new javax.swing.JLabel();
        TextoSenha = new javax.swing.JLabel();
        BotaaoCriar = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        Texto_Bem_vindo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Texto_Bem_vindo.setForeground(new java.awt.Color(255, 255, 255));
        Texto_Bem_vindo.setText("Bem-Vindo de Volta");

        Texto_AcesseConta.setBackground(new java.awt.Color(255, 255, 255));
        Texto_AcesseConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Texto_AcesseConta.setForeground(new java.awt.Color(255, 255, 255));
        Texto_AcesseConta.setText(" Sistema Acadêmico");

        Texto_AcesseConta1.setBackground(new java.awt.Color(255, 255, 255));
        Texto_AcesseConta1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Texto_AcesseConta1.setForeground(new java.awt.Color(255, 255, 255));
        Texto_AcesseConta1.setText("De Gestão De Alunos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Texto_Bem_vindo)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto_AcesseConta1)
                    .addComponent(Texto_AcesseConta))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(Texto_Bem_vindo)
                .addGap(18, 18, 18)
                .addComponent(Texto_AcesseConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto_AcesseConta1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TextoCrieConta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextoCrieConta.setForeground(new java.awt.Color(0, 255, 102));
        TextoCrieConta.setText("ACESSAR SUA CONTA");

        Nome_Usuario.setBackground(new java.awt.Color(245, 245, 245));

        Senha.setBackground(new java.awt.Color(245, 245, 245));
        Senha.addActionListener(this::SenhaActionPerformed);

        TextoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TextoUsuario.setText("Usuario");

        TextoSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TextoSenha.setText("Senha");

        BotaaoCriar.setBackground(new java.awt.Color(0, 255, 102));
        BotaaoCriar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaaoCriar.setForeground(new java.awt.Color(255, 255, 255));
        BotaaoCriar.setText("Entrar");
        BotaaoCriar.addActionListener(this::BotaaoCriarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TextoCrieConta)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TextoUsuario)
                                    .addGap(214, 214, 214))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TextoSenha)
                                                .addGap(200, 200, 200))
                                            .addComponent(Senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Nome_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(BotaaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TextoCrieConta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(BotaaoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void BotaaoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaaoCriarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaaoCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaaoCriar;
    private javax.swing.JTextField Nome_Usuario;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel TextoCrieConta;
    private javax.swing.JLabel TextoSenha;
    private javax.swing.JLabel TextoUsuario;
    private javax.swing.JLabel Texto_AcesseConta;
    private javax.swing.JLabel Texto_AcesseConta1;
    private javax.swing.JLabel Texto_Bem_vindo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
